---
application:
  name: "boutique-server"
  project: "Boutique-Store"
  organization: "QoveryCommunity"
  dockerfile: "./Dockerfile"
databases:
- type: "POSTGRESQL"
  name: "boutique"
  version: "12"
routers:
- name: "main-boutique-server"
  routes:
  - application_name: "boutique-server"
    paths:
    - "/*"
